Features/custom tabs collection view
Ievgen-Mykhailiuk/TabsCollectionView pull request #1
Opened 2022-09-01 13:12 UTC by Ievgen-Mykhailiuk

2022-09-01 13:43 UTC, Nikitax23 requested changes
на этом я пока остановлю свой ревью, потому что тут должна быть переиспользумая кастомная вьюха, наследник `UIView`. которую можно использовать на любом `UIViewController`. и так же, в любой проект чтоб можно было взять и перенести эту вьюху.

2022-09-01 13:43 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/Extensions/String+Extension.swift
> +    func widthOfString(usingFont font: UIFont) -> CGFloat {
`widthOfString`

зачем называть так метод, если мы и так знаем, widthOfЧто мы получаем? мы вызываем этот метод у строки) просто `textWidth`

2022-09-01 13:43 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsCollectionViewController.swift
> +    private var selectedTab: Int? {
`selectedTab` всегда есть!
по дефолту = .zero

2022-09-01 13:43 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsCollectionViewController.swift
> +        setupCollectionViewConstraints()
почему именно здесь ты это делаешь? почему не в initialSetup ?

2022-09-01 13:43 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsCollectionViewController.swift
> +
тут может быть только два варианта : 

- <= 3 табов, и - все остальные варианты. 
для них может быть всего один метод, внутри которого будет проверяться это условие и будет if #condition# {} else {}

2022-09-01 13:43 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsCollectionViewController.swift
> +            cell.isSelected()
1) методы `isSelected / isDeselected` называются, как геттеры. 
они должны называться setSelectedState / setDefaultState. 
а вообще, лучше их собрать в один метод, который будет принимать параметр: isSelected. 
то есть: `func setState(isSelected: Bool)`. 

А ВООБЩЕ 
этот метод , который написан выше - должен быть приватным! 
`configure` метод должен принимать параметр `isSelected` => `cell.configure(with: tabTitle, isSelected: indexPath.row == selectedTab)`, и внутри конфигура уже будет вызываться твой `setState` метод.

2022-09-07 13:01 UTC, Nikitax23 requested changes
в целом - хорошо. есть моменты к оптимизации

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/Extensions/String+Extension.swift
> +    func textWidth(usingFont font: UIFont) -> CGFloat {
`usingFont`
не надо так называть параметр. 
у тебя слово font повторяется. 
в таком случае просто достаточно using или with

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +    private let cellIdentifier = String(describing: TabsCollectionViewCell.self)
Нам здесь это не нужно уже

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +    private var selectedTab: Int = .zero {
`selectedTab`
наверное, это индекс, а не сам таб? 
потому что табы у нас - `String` элементы

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +        updateIndicatorPosition(index: .init(row: selectedTab, section: 0))
я думаю тут лучше вызвать `selectTab` метод

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +    private func updateIndicatorPosition(index: IndexPath) {
у нас одна секция здесь всего. 
метод может принимать просто `Int` . это будет передаваться в indexPath.item 
передал индекс интовый, и заинитил тут же в` layoutAttributesForItem(at: .init(item: index, section: .zero))`

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +            self.selectionIndicatorView.frame = CGRect(x: attributes.frame.origin.x,
можно вообще и так, но на самом деле высота `height` и `y` позиция никогда не меняются. они один раз задались и ничего делать больше не нужно с ними)

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +            self.selectionIndicatorView.makeRounded()
зачем закруглять вьюху каждый раз, если она основана на высоте, которая никогда не меняется, и она уже могла быть закругленной до этого?

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +        if dataSource.count <= 3 {
`3` что это такое  - мне непонятно. это magic number,  от которого нужно избавляться . код должен быть читабельным и легко модифицируемым

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +        var cellSize = CGSize()
`var cellSize = CGSize()`
некритично, но я бы предпочел 

`var cellSize: CGSize = .zero`

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +            let cellWidth = tabTitle.textWidth(usingFont: font) + 10
то же самое. что такое `10` - мне непонятно

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +        selectedTab = indexPath.row
так вот здесь тоже можно принимать просто `Int` индекс

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +        tabsCollectionView.scrollToItem(at: indexPath,
я бы сначала вызвал скролл, а потом уже апдейт индикатор позицию

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +        UIView.animate(withDuration: 0.3) {
длительность анимации можно вынести в константу. и я бы уменьшил немножко. до 0.2 попробуй. 
так же, можно добавить animationOptions , для красоты

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +final class TabsView: UIView {
рекомендую сделать так, чтоб эта вьюха так же принимала цвета: выбранный и невыбранный.
и они должны соответственно храниться, и передаваться между сабвьюхами.

2022-09-07 13:01 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: cellIdentifier,
переделать регистрацию и получение ячейки на новые методы

2022-09-08 10:36 UTC, Nikitax23 requested changes
уже гораздо лучше. осталось пару моментов к улучшению

2022-09-08 10:36 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/Protocols.swift
> +//
зачем тебе пустой файл?

2022-09-08 10:36 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsCollectionViewCell.swift
> +final class TabsCollectionViewCell:  BaseCollectionViewCell {
`final class TabsCollectionViewCell:  BaseCollectionViewCell`
лишний пробел

2022-09-08 10:36 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsCollectionViewCell.swift
> +    private func setState(isSelected: Bool,
не нужно передавать сюда цвета. 
цвета должны храниться у ячейки. 
один раз их передали в конфигуре, и запомнили их в свойства

2022-09-08 10:36 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsCollectionViewController.swift
> +        let tabsView = TabsView(dataSource: ["Bimmer", "Benz", "Bentley", "Bimmer", "Benz",
зачем тебе фрейм в ините? 
Используй констрейнты.

2022-09-08 10:36 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +            collectionView.leftAnchor.constraint(equalTo: self.leftAnchor, constant: 10),
как я вижу, отступ слева и справа у тебя одинаковые. (зачастую так и есть)
так ты используешь число отступа два раза , только с разным знаком. то есть, когда тебе надо будет поменять отступ, тебе надо поменять его в двух местах. Можно ведь это улучшить. Понимаешь о чём я?

2022-09-08 11:54 UTC, Ievgen-Mykhailiuk commented on TabsCollectionView/TabsCollectionView/Protocols.swift
> +//
Странно, у меня такого файла нет! Еще в прошлом ревью я заметил что ты указал на кое какие вещи которых у меня уже  были в коде(например у меня уже были новые методы .register and .cell) Желательно разобраться, может я что-то не так сделал?!

2022-09-08 15:16 UTC, Nikitax23 commented on TabsCollectionView/TabsCollectionView/TabsView.swift
> +    private func setIndicatorYCoordinate() {
`setIndicatorYCoordinate`
можно назвать `setSelectionIndicatorPosition`

2022-09-08 15:16 UTC, Nikitax23 approved these changes
Один момент с названием) 
Можно мержить после этого

2022-09-12 10:43 UTC, merged